services:
 # MAX761.local:
 #   container_name: MAX761.local
 #   image: "ghcr.io/pvkvicky2000/oracledb:empty"
 #   ports:
 #     - "1521:1521"
 #     - "5500:5500"
 #   environment:
 #     ORACLE_SID: MAXIMO761
 #     ORACLE_PDB: MAXIMOPDB
 #     ORACLE_PWD: maximo123
 #     ORACLE_EDITION: enterprise
 #     ORACLE_CHARACTERSET: AL32UTF8
 #     ENABLE_ARCHIVELOG: "false"
 #   volumes:
 #     - ./oracle/19c:/opt/oracle/oradata

  MAX761.local:
    container_name: MAX761.local
    hostname: MAX761.local
    image : "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "maximo_2012"
    volumes:
      - /Users/vijay/Docker-WAS-maximo/Anywhere/sql-server/data:/var/opt/mssql
  maximoui:
    container_name: Maximo-UI
    image: "websphere-liberty:21.0.0.7-full-java8-ibmjava"
    ports:
      - "9080:9080"
    volumes:
      - ./SMP/maximo/deployment/was-liberty-default/deployment/maximo-ui/maximo-ui-server:/config
  # ngnix:
  #   container_name: ngnix-load-balancer
  #   image: "nginx"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
